### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by vincentcox** [NextronSystems/ransomware-simulator#1]
Hi there,
I'm having some troubles with installing this, I tried `go get` to install straight from Github:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/9286611/168562371-f55e0f8a-c22a-4a58-9218-ce3b9ac41b9c.png">

But that doesn't seem to work out. How do you get it installed?

Thanks in advance!

**Comment by secDre4mer** [comment]
Hi Vincent, 

Thanks for opening the issue. I misdeclared the module path, which cause your issue. I've fixed this and `go install` now works as intended.

Note that you'll need to refer to `github.com/NextronSystems/ransomware-simulator/cmd` for the main package, e.g. with:

`go install github.com/NextronSystems/ransomware-simulator/cmd@latest`

**Comment by vincentcox** [comment]
Great, seems to work!

However, if I install it on a Windows, the installation gets interrupted:

![image](https://user-images.githubusercontent.com/9286611/168585376-20a962f2-a742-4417-ab64-a7829739d929.png)

I know it's a cat and mouse game to get this working, but how should people use this project? Modify the code themself to get a different signature on compilation?

**Comment by secDre4mer** [comment]
Hi Vincent, 

To some degree, this is wanted: After all, we simulate ransomware behaviour and AV detection is explicitly desired.

You could try to build the simulator using `https://github.com/burrowers/garble`. Might work or not, depending on how thorough Defender works with its sandbox.

**Comment by vincentcox** [comment]
Hi @secDre4mer,

That explanation makes sense! 

Thanks for the Go Obfuscater tip, looks like a neat tool!
